### ISSUE TITLE
Inclusion in fdroid

### ISSUE THREAD

**Issue by webhat** [MaximeBeasse/KeyDecoder#2]
Hi,

do you have any issue with the app being inlcuded in [fdroid](https://f-droid.org/)?

**Comment by MaximeBeasse** [comment]
We will indeed make it availaible on fdroid soon. Keep in touch 😉

**Comment by webhat** [comment]
To help get the ball rolling I pre-submitted for inclusion. The reviewer said you need to make some changes, including using a OSI approved license.

[thread](https://gitlab.com/fdroid/rfp/-/issues/1604#note_476099948)

**Comment by MaximeBeasse** [comment]
Hi, sorry for the late response.

We are not going to modify the license to an OSI approved license. We, as developpers, have chosen the Aladdin license to publicly share the source code for free but avoid any third party to make money by any means possible with this app.

It is possible to build this app as is to an .apk file and install it on your phone, feel free to do it.
