### ISSUE TITLE
Feature Request: F-Droid releases

### ISSUE THREAD

**Issue by qkqsb** [MaximeBeasse/KeyDecoder#4]
Hello,

this is an excellent open source project, and one that would be made more accessible by listing it on F-Droid. Do you think this would be possible?

**Comment by MuntashirAkon** [comment]
This is not an open source project.

**Comment by ajmeese7** [comment]
@MuntashirAkon how is this not an open-source project?

**Comment by MuntashirAkon** [comment]
AFPL is not an open source license. It's a source-available license meaning you're not allowed to reproduce, modify or redistribute the app.

**Comment by ghost** [comment]
> @MuntashirAkon how is this not an open-source project?

looks like it's technically a source-available license, derived from the GNU GPL

**Comment by mh-** [comment]
https://en.wikipedia.org/wiki/Aladdin_Free_Public_License states "Despite the name, the [Free Software Foundation](https://en.wikipedia.org/wiki/Free_Software_Foundation) does not consider the AFPL a [free software license](https://en.wikipedia.org/wiki/Free_software_licence),[[1]](https://en.wikipedia.org/wiki/Aladdin_Free_Public_License#cite_note-fsflist-1) neither the OSI consider it an [open-source license](https://en.wikipedia.org/wiki/Open-source_license), nor does it fall under the [Copyfree](https://en.wikipedia.org/wiki/Copyfree) Standard definition.[[4]](https://en.wikipedia.org/wiki/Aladdin_Free_Public_License#cite_note-4)".

https://f-droid.org/en/docs/Inclusion_Policy/ states: "All applications in the repository must be Free, Libre and Open Source Software (FLOSS) [...] To determine which licenses are FLOSS, We defer to widely trusted organizations that have a proven track record. Specifically, we acknowledge these standards: [DFSG](https://wiki.debian.org/DFSGLicenses), [FSF](https://www.fsf.org/licensing), [GNU](https://www.gnu.org/licenses/license-list.html), and [OSI](https://opensource.org/licenses)."

So it doesn't look like F-Droid would accept this license.

**Comment by MaximeBeasse** [comment]
Indeed, we chose the Aladdin Free Public License to avoid any commercial use of this software.
We are aware it does not make it truely _Open Source_ but since the functionnalities featured in this app may be be used for illegal activities, we feel it should not be marketable.

The release of KeyDecoder on F-Droid is thus not possible. But still, it is possible to build an APK quite easily, and if you don't mind having a Google Play account, the app is free to download and still does not track any personal data nor does it connect to the internet, as the code shows.

KeyDecoder is meant as an educational software, and aims to sensibilize the public to keep their mechanical keys private.

**Comment by MuntashirAkon** [comment]
> We are aware it does not make it truely _Open Source_ but since the functionnalities featured in this app may be be used for illegal activities, we feel it should not be marketable.

You do realise that those who might use it for illegal activities would not pay any attention to the license. When something is available online, no licensing in the world can prevent it from being abused or misused. Therefore, how this argument is justifiable is beyond me. Also, since this project is written using a framework which, with a few changes, can be made difficult to prove that the work is in fact a derivation of this work without looking at the source code. It would be rather difficult for you to find a copycat, and even when you find one, it would be quite difficult to prove that it is a copycat of this project but then, this would only work in a few stores such as Google Play Store.

**Comment by ghost** [comment]
> > We are aware it does not make it truely _Open Source_ but since the functionnalities featured in this app may be be used for illegal activities, we feel it should not be marketable.
> 
> You do realise that those who might use it for illegal activities would not pay any attention to the license. When something is available online, no licensing in the world can prevent it from being abused or misused. Therefore, how this argument is justifiable is beyond me. Also, since this project is written using a framework which, with a few changes, can be made difficult to prove that the work is in fact a derivation of this work without looking at the source code. It would be rather difficult for you to find a copycat, and even when you find one, it would be quite difficult to prove that it is a copycat of this project but then, this would only work in a few stores such as Google Play Store.

A license for driving doesn't stop anyone from jumping in a car and putting their foot on the gas either, but it is still illegal, and if someone uses it illegally and they are caught, they are culpable. In this case, it would not be the software developer.

**Comment by MuntashirAkon** [comment]
> In this case, it would not be the software developer.

Most open source licenses do not hold the original author responsible for the illegal use by a derived work. If it wasn't the case, nobody would use any open source license.

**Comment by ghost** [comment]
> > In this case, it would not be the software developer.
> 
> Most open source licenses do not hold the original author responsible for the illegal use by a derived work. If it wasn't the case, nobody would use any open source license.

Right, and if you take 30 seconds to read about the AFPL you would see it's not considered an open-source license.

**Comment by MuntashirAkon** [comment]
> if you take 30 seconds to read about the AFPL you would see it's not considered an open-source license.

What are you talking about? I was the first person here to indicate that the project is not an open source project, thus, unsuitable for F-Droid as per its inclusion policy.

**Comment by ghost** [comment]
> > if you take 30 seconds to read about the AFPL you would see it's not considered an open-source license.
> 
> What are you talking about? I was the first person here to indicate that the project is not an open source project, thus, unsuitable for F-Droid as per its inclusion policy.

I can see that... Nevertheless, I can understand what the devs mean by choosing the AFPL and given their explanation above ("Indeed, we chose the Aladdin Free Public License to avoid any commercial use of this software.") , I digress.

**Comment by MuntashirAkon** [comment]
> I can understand what the devs mean by choosing the AFPL and given their explanation above ("Indeed, we chose the Aladdin Free Public License to avoid any commercial use of this software.") , I digress.

I would have said nothing if the target was to _solely_ prevent the commercial use of the software. Mega.nz, for instance, published its source code under a source-available license and serves a good example. However, my argument was against the reasoning that was given to justify the licensing i.e. preventing _illegal activities_ as if the source was made available in _good faith_. I stated that the reasoning does not justify the licensing at all.

**Comment by muelli** [comment]
Would re-licensing be an option?

**Comment by MaximeBeasse** [comment]
No, it's not an option.
