### ISSUE TITLE
Incompatible with newest android version? 

### ISSUE THREAD

**Issue by mazonaught** [MaximeBeasse/KeyDecoder#9]
Get "this app isn't available for your device because it was made for an older version of Android" message on play store

**Comment by MaximeBeasse** [comment]
Yeah, I've seen this problem. Could you give me your device's model and brand please?
I will publish an update in a few weeks when I'll have time.

**Comment by mazonaught** [comment]
I have a samsung s10e, android 12. Thank you, and no rush, just wanted to let you know

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by bluenazgul** [comment]
Same issue on Google Pixel 7 on Android 13

**Comment by aixueli-liu** [comment]
oppo a58也这样提示

**Comment by h0r4ci0** [comment]
Same with Nothing Phone (Android 13)

**Comment by ChucklesNuts** [comment]
Android is a kerfuffle of inconsistencies. And it annoys me to no end how an older version of android can run an app but not a newer version.

App works on my LG v-30 with android 9 but my samsung note 10plus with android 12 it says unavailable. the model number is SM-N975U1

**Comment by BangDroid** [comment]
Just so I don't waste my time trying, if I build it myself, will it work on newer android versions?

**Comment by MaximeBeasse** [comment]
I have published an update. Can anyone with a newer android phone that previously could not run the app please test it?
The APKs are now available in the "Release" section of the repo.

**Comment by BangDroid** [comment]
Can confirm Play store version successfully installs. Samsung Galaxy S10, Android 12.

Cropping the image appears to have some problem. I was getting an area outside of all cropping lines. Whether I take photo in app, or use existing image. To mitigate this I pre-cropped the image very close to the card with photo editor and then performed the cropping stage which was successful.

The rest of the app appears to function as expected. I tested with a known key and measurements were very close.

**Comment by MaximeBeasse** [comment]
I can"t seem to reproduce your bug. I am closing this issue as it now works on Android 13.
I would gladly look into this crop problem is you provide a picture (no key) that fails to crop in a new issue.
